/* ============================================================
   js/i18n.js — LanceDEX built-in interface translation.
   CSP-safe: no external scripts, no network calls. Translates the
   site's own UI (menus, buttons, headings, labels) using bundled
   dictionaries. Auto-detects the visitor's browser language and
   remembers a manual choice (localStorage "ld-lang").
   Game/guide body text stays in the language it was written in.
   ============================================================ */
(function () {
  "use strict";

  // Supported languages -> native display name (English is the source).
  var SUPPORTED = {
    en: "English", es: "Espanol", pt: "Portugues", fr: "Francais", de: "Deutsch",
    ko: "Hangugeo", ja: "Nihongo", zh: "Zhongwen", vi: "Tieng Viet", th: "Thai", id: "Indonesia"
  };
  // Proper native names (kept separate so the file stays ASCII-readable above).
  var NATIVE = {
    en: "English", es: "Español", pt: "Português", fr: "Français", de: "Deutsch",
    ko: "한국어", ja: "日本語", zh: "中文",
    vi: "Tiếng Việt", th: "ไทย", id: "Bahasa Indonesia"
  };

  // dict[lang][englishSource] = translation. English falls through untouched.
  var DICT = {
    es: {"Home":"Inicio","Upcoming games":"Próximos juegos","Guides":"Guías","All games":"Todos los juegos","Database":"Base de datos","Characters":"Personajes","Tier Lists":"Listas de niveles","Tier List":"Lista de niveles","Roles & Effects":"Roles y efectos","Tools":"Herramientas","Team Builder":"Creador de equipos","Events & Bosses":"Eventos y jefes","Popular games":"Juegos populares","New games":"Juegos nuevos","All supported games":"Todos los juegos disponibles","Upcoming releases":"Próximos lanzamientos","Latest guides":"Últimas guías","All upcoming games":"Todos los próximos juegos","Nothing announced yet.":"Nada anunciado todavía.","Database & Tools":"Base de datos y herramientas","Reviews, ratings and recommended builds":"Análisis, valoraciones y builds recomendadas","Every effect mapped to the heroes that provide it":"Cada efecto asignado a los héroes que lo aportan","Plan synergy and team compositions":"Planifica sinergias y composiciones de equipo","Optimal compositions and mechanics":"Composiciones óptimas y mecánicas","No guides yet.":"Aún no hay guías.","About the tier list":"Sobre la lista de niveles","Criteria":"Criterios","Changelog":"Registro de cambios","No entries yet.":"Aún no hay entradas.","No characters match those filters.":"Ningún personaje coincide con esos filtros.","↺ Reset":"↺ Restablecer","Search characters...":"Buscar personajes...","Review":"Análisis","Ratings":"Valoraciones","Recommended build":"Build recomendada","Pros":"Pros","Cons":"Contras","All guides":"Todas las guías","Every guide across every game we cover.":"Todas las guías de todos los juegos que cubrimos.","Upcoming Games Tracker":"Rastreador de próximos juegos","Release date announced":"Fecha de lanzamiento anunciada","Games without a release date":"Juegos sin fecha de lanzamiento","Search for a game...":"Buscar un juego...","Release date":"Fecha de lanzamiento","Platforms":"Plataformas","Publisher":"Editora","Website":"Sitio web","Unknown":"Desconocida","Search heroes or effects...":"Buscar héroes o efectos...","Your Team":"Tu equipo","Suggested Presets":"Plantillas sugeridas","Copy URL":"Copiar URL","Reset Team":"Reiniciar equipo","Select Character":"Seleccionar personaje","Back to top":"Volver arriba","Theme":"Tema","Language":"Idioma","Last updated:":"Última actualización:","__showing__":"Mostrando {n} personajes","__updated__":"Actualizado {d}","__patch_updated__":"Servidor {p} • Actualizado {d}","Settings":"Ajustes","Appearance":"Apariencia","Light":"Claro","Dark":"Oscuro","Scroll down for more settings":"Desplázate para ver más ajustes","More settings":"Más ajustes","Close":"Cerrar","A new version is available":"Hay una nueva versión disponible","Update":"Actualizar","Scroll up to close":"Desplázate hacia arriba para cerrar","__ranked__":"Cada personaje clasificado en {n} modos de juego"},
    pt: {"Home":"Início","Upcoming games":"Próximos jogos","Guides":"Guias","All games":"Todos os jogos","Database":"Banco de dados","Characters":"Personagens","Tier Lists":"Tier lists","Tier List":"Tier list","Roles & Effects":"Funções e efeitos","Tools":"Ferramentas","Team Builder":"Montador de times","Events & Bosses":"Eventos e chefes","Popular games":"Jogos populares","New games":"Novos jogos","All supported games":"Todos os jogos disponíveis","Upcoming releases":"Próximos lançamentos","Latest guides":"Guias recentes","All upcoming games":"Todos os próximos jogos","Nothing announced yet.":"Nada anunciado ainda.","Database & Tools":"Banco de dados e ferramentas","Reviews, ratings and recommended builds":"Análises, notas e builds recomendadas","Every effect mapped to the heroes that provide it":"Cada efeito mapeado aos heróis que o fornecem","Plan synergy and team compositions":"Planeje sinergias e composições de time","Optimal compositions and mechanics":"Composições ideais e mecânicas","No guides yet.":"Ainda não há guias.","About the tier list":"Sobre a tier list","Criteria":"Critérios","Changelog":"Registro de alterações","No entries yet.":"Ainda não há entradas.","No characters match those filters.":"Nenhum personagem corresponde a esses filtros.","↺ Reset":"↺ Redefinir","Search characters...":"Buscar personagens...","Review":"Análise","Ratings":"Notas","Recommended build":"Build recomendada","Pros":"Prós","Cons":"Contras","All guides":"Todos os guias","Every guide across every game we cover.":"Todos os guias de todos os jogos que cobrimos.","Upcoming Games Tracker":"Rastreador de próximos jogos","Release date announced":"Data de lançamento anunciada","Games without a release date":"Jogos sem data de lançamento","Search for a game...":"Buscar um jogo...","Release date":"Data de lançamento","Platforms":"Plataformas","Publisher":"Distribuidora","Website":"Site","Unknown":"Desconhecida","Search heroes or effects...":"Buscar heróis ou efeitos...","Your Team":"Seu time","Suggested Presets":"Modelos sugeridos","Copy URL":"Copiar URL","Reset Team":"Redefinir time","Select Character":"Selecionar personagem","Back to top":"Voltar ao topo","Theme":"Tema","Language":"Idioma","Last updated:":"Última atualização:","__showing__":"Mostrando {n} personagens","__updated__":"Atualizado em {d}","__patch_updated__":"Servidor {p} • Atualizado em {d}","Settings":"Configurações","Appearance":"Aparência","Light":"Claro","Dark":"Escuro","Scroll down for more settings":"Role para mais configurações","More settings":"Mais configurações","Close":"Fechar","A new version is available":"Há uma nova versão disponível","Update":"Atualizar","Scroll up to close":"Role para cima para fechar","__ranked__":"Todos os personagens classificados em {n} modos de jogo"},
    fr: {"Home":"Accueil","Upcoming games":"Jeux à venir","Guides":"Guides","All games":"Tous les jeux","Database":"Base de données","Characters":"Personnages","Tier Lists":"Tier lists","Tier List":"Tier list","Roles & Effects":"Rôles et effets","Tools":"Outils","Team Builder":"Créateur d'équipe","Events & Bosses":"Événements et boss","Popular games":"Jeux populaires","New games":"Nouveaux jeux","All supported games":"Tous les jeux pris en charge","Upcoming releases":"Sorties à venir","Latest guides":"Derniers guides","All upcoming games":"Tous les jeux à venir","Nothing announced yet.":"Rien d'annoncé pour l'instant.","Database & Tools":"Base de données et outils","Reviews, ratings and recommended builds":"Analyses, notes et builds recommandés","Every effect mapped to the heroes that provide it":"Chaque effet associé aux héros qui le fournissent","Plan synergy and team compositions":"Planifiez les synergies et les compositions d'équipe","Optimal compositions and mechanics":"Compositions optimales et mécaniques","No guides yet.":"Pas encore de guides.","About the tier list":"À propos de la tier list","Criteria":"Critères","Changelog":"Journal des modifications","No entries yet.":"Aucune entrée pour l'instant.","No characters match those filters.":"Aucun personnage ne correspond à ces filtres.","↺ Reset":"↺ Réinitialiser","Search characters...":"Rechercher des personnages...","Review":"Analyse","Ratings":"Notes","Recommended build":"Build recommandé","Pros":"Avantages","Cons":"Inconvénients","All guides":"Tous les guides","Every guide across every game we cover.":"Tous les guides de tous les jeux que nous couvrons.","Upcoming Games Tracker":"Suivi des jeux à venir","Release date announced":"Date de sortie annoncée","Games without a release date":"Jeux sans date de sortie","Search for a game...":"Rechercher un jeu...","Release date":"Date de sortie","Platforms":"Plateformes","Publisher":"Éditeur","Website":"Site web","Unknown":"Inconnue","Search heroes or effects...":"Rechercher des héros ou des effets...","Your Team":"Votre équipe","Suggested Presets":"Préréglages suggérés","Copy URL":"Copier l'URL","Reset Team":"Réinitialiser l'équipe","Select Character":"Sélectionner un personnage","Back to top":"Retour en haut","Theme":"Thème","Language":"Langue","Last updated:":"Dernière mise à jour :","__showing__":"Affichage de {n} personnages","__updated__":"Mis à jour le {d}","__patch_updated__":"Serveur {p} • Mis à jour le {d}","Settings":"Paramètres","Appearance":"Apparence","Light":"Clair","Dark":"Sombre","Scroll down for more settings":"Faites défiler pour plus d'options","More settings":"Plus d'options","Close":"Fermer","A new version is available":"Une nouvelle version est disponible","Update":"Mettre à jour","Scroll up to close":"Faites défiler vers le haut pour fermer","__ranked__":"Chaque personnage classé dans {n} modes de jeu"},
    de: {"Home":"Startseite","Upcoming games":"Kommende Spiele","Guides":"Guides","All games":"Alle Spiele","Database":"Datenbank","Characters":"Charaktere","Tier Lists":"Tier-Listen","Tier List":"Tier-Liste","Roles & Effects":"Rollen & Effekte","Tools":"Werkzeuge","Team Builder":"Team-Builder","Events & Bosses":"Events & Bosse","Popular games":"Beliebte Spiele","New games":"Neue Spiele","All supported games":"Alle unterstützten Spiele","Upcoming releases":"Kommende Veröffentlichungen","Latest guides":"Neueste Guides","All upcoming games":"Alle kommenden Spiele","Nothing announced yet.":"Noch nichts angekündigt.","Database & Tools":"Datenbank & Werkzeuge","Reviews, ratings and recommended builds":"Rezensionen, Bewertungen und empfohlene Builds","Every effect mapped to the heroes that provide it":"Jeder Effekt den Helden zugeordnet, die ihn bereitstellen","Plan synergy and team compositions":"Plane Synergien und Teamzusammenstellungen","Optimal compositions and mechanics":"Optimale Zusammenstellungen und Mechaniken","No guides yet.":"Noch keine Guides.","About the tier list":"Über die Tier-Liste","Criteria":"Kriterien","Changelog":"Änderungsprotokoll","No entries yet.":"Noch keine Einträge.","No characters match those filters.":"Keine Charaktere entsprechen diesen Filtern.","↺ Reset":"↺ Zurücksetzen","Search characters...":"Charaktere suchen...","Review":"Rezension","Ratings":"Bewertungen","Recommended build":"Empfohlener Build","Pros":"Vorteile","Cons":"Nachteile","All guides":"Alle Guides","Every guide across every game we cover.":"Alle Guides zu allen Spielen, die wir abdecken.","Upcoming Games Tracker":"Tracker für kommende Spiele","Release date announced":"Erscheinungsdatum angekündigt","Games without a release date":"Spiele ohne Erscheinungsdatum","Search for a game...":"Nach einem Spiel suchen...","Release date":"Erscheinungsdatum","Platforms":"Plattformen","Publisher":"Publisher","Website":"Webseite","Unknown":"Unbekannt","Search heroes or effects...":"Helden oder Effekte suchen...","Your Team":"Dein Team","Suggested Presets":"Vorgeschlagene Vorlagen","Copy URL":"URL kopieren","Reset Team":"Team zurücksetzen","Select Character":"Charakter auswählen","Back to top":"Nach oben","Theme":"Design","Language":"Sprache","Last updated:":"Zuletzt aktualisiert:","__showing__":"Zeige {n} Charaktere","__updated__":"Aktualisiert am {d}","__patch_updated__":"{p}-Server • Aktualisiert am {d}","Settings":"Einstellungen","Appearance":"Darstellung","Light":"Hell","Dark":"Dunkel","Scroll down for more settings":"Zum Anzeigen weiterer Einstellungen scrollen","More settings":"Mehr Einstellungen","Close":"Schließen","A new version is available":"Eine neue Version ist verfügbar","Update":"Aktualisieren","Scroll up to close":"Nach oben scrollen zum Schließen","__ranked__":"Jeder Charakter in {n} Spielmodi eingestuft"},
    ko: {"Home":"홈","Upcoming games":"출시 예정 게임","Guides":"가이드","All games":"모든 게임","Database":"데이터베이스","Characters":"캐릭터","Tier Lists":"티어 리스트","Tier List":"티어 리스트","Roles & Effects":"역할 및 효과","Tools":"도구","Team Builder":"팀 빌더","Events & Bosses":"이벤트 및 보스","Popular games":"인기 게임","New games":"새 게임","All supported games":"지원하는 모든 게임","Upcoming releases":"출시 예정","Latest guides":"최신 가이드","All upcoming games":"모든 출시 예정 게임","Nothing announced yet.":"아직 발표된 내용이 없습니다.","Database & Tools":"데이터베이스 및 도구","Reviews, ratings and recommended builds":"리뷰, 평가 및 추천 빌드","Every effect mapped to the heroes that provide it":"각 효과를 제공하는 영웅과 매핑","Plan synergy and team compositions":"시너지와 팀 조합을 계획하세요","Optimal compositions and mechanics":"최적의 조합과 메커니즘","No guides yet.":"아직 가이드가 없습니다.","About the tier list":"티어 리스트 소개","Criteria":"기준","Changelog":"변경 내역","No entries yet.":"아직 항목이 없습니다.","No characters match those filters.":"해당 필터에 맞는 캐릭터가 없습니다.","↺ Reset":"↺ 초기화","Search characters...":"캐릭터 검색...","Review":"리뷰","Ratings":"평가","Recommended build":"추천 빌드","Pros":"장점","Cons":"단점","All guides":"모든 가이드","Every guide across every game we cover.":"저희가 다루는 모든 게임의 모든 가이드.","Upcoming Games Tracker":"출시 예정 게임 트래커","Release date announced":"출시일 발표됨","Games without a release date":"출시일 미정 게임","Search for a game...":"게임 검색...","Release date":"출시일","Platforms":"플랫폼","Publisher":"퍼블리셔","Website":"웹사이트","Unknown":"미정","Search heroes or effects...":"영웅 또는 효과 검색...","Your Team":"내 팀","Suggested Presets":"추천 프리셋","Copy URL":"URL 복사","Reset Team":"팀 초기화","Select Character":"캐릭터 선택","Back to top":"맨 위로","Theme":"테마","Language":"언어","Last updated:":"마지막 업데이트:","__showing__":"{n}개 캐릭터 표시 중","__updated__":"{d} 업데이트","__patch_updated__":"{p} 서버 • {d} 업데이트","Settings":"설정","Appearance":"화면 모드","Light":"라이트","Dark":"다크","Scroll down for more settings":"더 많은 설정을 보려면 아래로 스크롤","More settings":"더 많은 설정","Close":"닫기","A new version is available":"새 버전이 있습니다","Update":"업데이트","Scroll up to close":"위로 스크롤하여 닫기","__ranked__":"{n}개 게임 모드에서 순위가 매겨진 모든 캐릭터"},
    ja: {"Home":"ホーム","Upcoming games":"近日登場のゲーム","Guides":"ガイド","All games":"すべてのゲーム","Database":"データベース","Characters":"キャラクター","Tier Lists":"ティアリスト","Tier List":"ティアリスト","Roles & Effects":"ロールと効果","Tools":"ツール","Team Builder":"チームビルダー","Events & Bosses":"イベントとボス","Popular games":"人気のゲーム","New games":"新作ゲーム","All supported games":"対応ゲーム一覧","Upcoming releases":"今後のリリース","Latest guides":"最新ガイド","All upcoming games":"近日登場のゲーム一覧","Nothing announced yet.":"まだ発表はありません。","Database & Tools":"データベースとツール","Reviews, ratings and recommended builds":"レビュー、評価、おすすめビルド","Every effect mapped to the heroes that provide it":"各効果を付与するヒーローに対応","Plan synergy and team compositions":"シナジーとチーム編成を計画","Optimal compositions and mechanics":"最適な編成とメカニクス","No guides yet.":"まだガイドはありません。","About the tier list":"ティアリストについて","Criteria":"基準","Changelog":"変更履歴","No entries yet.":"まだ項目がありません。","No characters match those filters.":"そのフィルターに一致するキャラクターはいません。","↺ Reset":"↺ リセット","Search characters...":"キャラクターを検索...","Review":"レビュー","Ratings":"評価","Recommended build":"おすすめビルド","Pros":"長所","Cons":"短所","All guides":"すべてのガイド","Every guide across every game we cover.":"当サイトが扱う全ゲームの全ガイド。","Upcoming Games Tracker":"近日登場ゲームトラッカー","Release date announced":"リリース日発表済み","Games without a release date":"リリース日未定のゲーム","Search for a game...":"ゲームを検索...","Release date":"リリース日","Platforms":"プラットフォーム","Publisher":"パブリッシャー","Website":"ウェブサイト","Unknown":"未定","Search heroes or effects...":"ヒーローまたは効果を検索...","Your Team":"あなたのチーム","Suggested Presets":"おすすめプリセット","Copy URL":"URLをコピー","Reset Team":"チームをリセット","Select Character":"キャラクターを選択","Back to top":"トップへ戻る","Theme":"テーマ","Language":"言語","Last updated:":"最終更新:","__showing__":"{n}体のキャラクターを表示中","__updated__":"{d} 更新","__patch_updated__":"{p}サーバー • {d} 更新","Settings":"設定","Appearance":"外観","Light":"ライト","Dark":"ダーク","Scroll down for more settings":"下にスクロールして詳細設定","More settings":"詳細設定","Close":"閉じる","A new version is available":"新しいバージョンがあります","Update":"更新","Scroll up to close":"上にスクロールで閉じる","__ranked__":"{n}のゲームモードでランク付けされた全キャラクター"},
    zh: {"Home":"首页","Upcoming games":"即将推出的游戏","Guides":"攻略","All games":"所有游戏","Database":"数据库","Characters":"角色","Tier Lists":"梯度榜","Tier List":"梯度榜","Roles & Effects":"定位与效果","Tools":"工具","Team Builder":"队伍编成","Events & Bosses":"活动与首领","Popular games":"热门游戏","New games":"新游戏","All supported games":"所有支持的游戏","Upcoming releases":"即将上线","Latest guides":"最新攻略","All upcoming games":"所有即将推出的游戏","Nothing announced yet.":"暂无公告。","Database & Tools":"数据库与工具","Reviews, ratings and recommended builds":"评测、评分与推荐配装","Every effect mapped to the heroes that provide it":"每种效果对应提供它的英雄","Plan synergy and team compositions":"规划羁绊与队伍搭配","Optimal compositions and mechanics":"最佳阵容与机制","No guides yet.":"暂无攻略。","About the tier list":"关于梯度榜","Criteria":"评定标准","Changelog":"更新日志","No entries yet.":"暂无条目。","No characters match those filters.":"没有符合这些筛选条件的角色。","↺ Reset":"↺ 重置","Search characters...":"搜索角色...","Review":"评测","Ratings":"评分","Recommended build":"推荐配装","Pros":"优点","Cons":"缺点","All guides":"所有攻略","Every guide across every game we cover.":"我们涵盖的所有游戏的全部攻略。","Upcoming Games Tracker":"新游追踪","Release date announced":"已公布发售日期","Games without a release date":"尚未公布发售日期的游戏","Search for a game...":"搜索游戏...","Release date":"发售日期","Platforms":"平台","Publisher":"发行商","Website":"官网","Unknown":"未知","Search heroes or effects...":"搜索英雄或效果...","Your Team":"你的队伍","Suggested Presets":"推荐预设","Copy URL":"复制链接","Reset Team":"重置队伍","Select Character":"选择角色","Back to top":"回到顶部","Theme":"主题","Language":"语言","Last updated:":"最后更新：","__showing__":"显示 {n} 个角色","__updated__":"更新于 {d}","__patch_updated__":"{p} 服务器 • 更新于 {d}","Settings":"设置","Appearance":"外观","Light":"浅色","Dark":"深色","Scroll down for more settings":"向下滚动查看更多设置","More settings":"更多设置","Close":"关闭","A new version is available":"有新版本可用","Update":"更新","Scroll up to close":"向上滚动关闭","__ranked__":"在 {n} 种游戏模式中评级的所有角色"},
    vi: {"Home":"Trang chủ","Upcoming games":"Trò chơi sắp ra mắt","Guides":"Hướng dẫn","All games":"Tất cả trò chơi","Database":"Cơ sở dữ liệu","Characters":"Nhân vật","Tier Lists":"Bảng xếp hạng","Tier List":"Bảng xếp hạng","Roles & Effects":"Vai trò & Hiệu ứng","Tools":"Công cụ","Team Builder":"Trình tạo đội hình","Events & Bosses":"Sự kiện & Boss","Popular games":"Trò chơi phổ biến","New games":"Trò chơi mới","All supported games":"Tất cả trò chơi được hỗ trợ","Upcoming releases":"Sắp phát hành","Latest guides":"Hướng dẫn mới nhất","All upcoming games":"Tất cả trò chơi sắp ra mắt","Nothing announced yet.":"Chưa có thông báo nào.","Database & Tools":"Cơ sở dữ liệu & Công cụ","Reviews, ratings and recommended builds":"Đánh giá, xếp hạng và build đề xuất","Every effect mapped to the heroes that provide it":"Mỗi hiệu ứng gắn với các hero cung cấp nó","Plan synergy and team compositions":"Lên kế hoạch phối hợp và đội hình","Optimal compositions and mechanics":"Đội hình tối ưu và cơ chế","No guides yet.":"Chưa có hướng dẫn nào.","About the tier list":"Giới thiệu bảng xếp hạng","Criteria":"Tiêu chí","Changelog":"Nhật ký thay đổi","No entries yet.":"Chưa có mục nào.","No characters match those filters.":"Không có nhân vật nào khớp với bộ lọc đó.","↺ Reset":"↺ Đặt lại","Search characters...":"Tìm nhân vật...","Review":"Đánh giá","Ratings":"Xếp hạng","Recommended build":"Build đề xuất","Pros":"Ưu điểm","Cons":"Nhược điểm","All guides":"Tất cả hướng dẫn","Every guide across every game we cover.":"Tất cả hướng dẫn cho mọi trò chơi chúng tôi đề cập.","Upcoming Games Tracker":"Theo dõi trò chơi sắp ra mắt","Release date announced":"Đã công bố ngày phát hành","Games without a release date":"Trò chơi chưa có ngày phát hành","Search for a game...":"Tìm một trò chơi...","Release date":"Ngày phát hành","Platforms":"Nền tảng","Publisher":"Nhà phát hành","Website":"Trang web","Unknown":"Chưa rõ","Search heroes or effects...":"Tìm hero hoặc hiệu ứng...","Your Team":"Đội của bạn","Suggested Presets":"Mẫu gợi ý","Copy URL":"Sao chép URL","Reset Team":"Đặt lại đội","Select Character":"Chọn nhân vật","Back to top":"Lên đầu trang","Theme":"Giao diện","Language":"Ngôn ngữ","Last updated:":"Cập nhật lần cuối:","__showing__":"Đang hiển thị {n} nhân vật","__updated__":"Cập nhật {d}","__patch_updated__":"Máy chủ {p} • Cập nhật {d}","Settings":"Cài đặt","Appearance":"Giao diện","Light":"Sáng","Dark":"Tối","Scroll down for more settings":"Cuộn xuống để xem thêm cài đặt","More settings":"Thêm cài đặt","Close":"Đóng","A new version is available":"Đã có phiên bản mới","Update":"Cập nhật","Scroll up to close":"Cuộn lên để đóng","__ranked__":"Mọi nhân vật được xếp hạng trên {n} chế độ chơi"},
    th: {"Home":"หน้าแรก","Upcoming games":"เกมที่กำลังจะมา","Guides":"ไกด์","All games":"เกมทั้งหมด","Database":"ฐานข้อมูล","Characters":"ตัวละคร","Tier Lists":"ทีเยอร์ลิสต์","Tier List":"ทีเยอร์ลิสต์","Roles & Effects":"บทบาทและเอฟเฟกต์","Tools":"เครื่องมือ","Team Builder":"ตัวจัดทีม","Events & Bosses":"อีเวนต์และบอส","Popular games":"เกมยอดนิยม","New games":"เกมใหม่","All supported games":"เกมที่รองรับทั้งหมด","Upcoming releases":"กำลังจะเปิดตัว","Latest guides":"ไกด์ล่าสุด","All upcoming games":"เกมที่กำลังจะมาทั้งหมด","Nothing announced yet.":"ยังไม่มีการประกาศ","Database & Tools":"ฐานข้อมูลและเครื่องมือ","Reviews, ratings and recommended builds":"รีวิว คะแนน และบิลด์แนะนำ","Every effect mapped to the heroes that provide it":"จับคู่แต่ละเอฟเฟกต์กับฮีโร่ที่มอบให้","Plan synergy and team compositions":"วางแผนการผสานพลังและการจัดทีม","Optimal compositions and mechanics":"การจัดทีมและกลไกที่เหมาะสมที่สุด","No guides yet.":"ยังไม่มีไกด์","About the tier list":"เกี่ยวกับทีเยอร์ลิสต์","Criteria":"เกณฑ์","Changelog":"บันทึกการเปลี่ยนแปลง","No entries yet.":"ยังไม่มีรายการ","No characters match those filters.":"ไม่มีตัวละครที่ตรงกับตัวกรองเหล่านั้น","↺ Reset":"↺ รีเซ็ต","Search characters...":"ค้นหาตัวละคร...","Review":"รีวิว","Ratings":"คะแนน","Recommended build":"บิลด์แนะนำ","Pros":"ข้อดี","Cons":"ข้อเสีย","All guides":"ไกด์ทั้งหมด","Every guide across every game we cover.":"ไกด์ทั้งหมดของทุกเกมที่เราครอบคลุม","Upcoming Games Tracker":"ตัวติดตามเกมที่กำลังจะมา","Release date announced":"ประกาศวันวางจำหน่ายแล้ว","Games without a release date":"เกมที่ยังไม่มีวันวางจำหน่าย","Search for a game...":"ค้นหาเกม...","Release date":"วันวางจำหน่าย","Platforms":"แพลตฟอร์ม","Publisher":"ผู้จัดจำหน่าย","Website":"เว็บไซต์","Unknown":"ไม่ทราบ","Search heroes or effects...":"ค้นหาฮีโร่หรือเอฟเฟกต์...","Your Team":"ทีมของคุณ","Suggested Presets":"พรีเซ็ตแนะนำ","Copy URL":"คัดลอก URL","Reset Team":"รีเซ็ตทีม","Select Character":"เลือกตัวละคร","Back to top":"กลับขึ้นบน","Theme":"ธีม","Language":"ภาษา","Last updated:":"อัปเดตล่าสุด:","__showing__":"กำลังแสดง {n} ตัวละคร","__updated__":"อัปเดต {d}","__patch_updated__":"เซิร์ฟเวอร์ {p} • อัปเดต {d}","Settings":"การตั้งค่า","Appearance":"ลักษณะ","Light":"สว่าง","Dark":"มืด","Scroll down for more settings":"เลื่อนลงเพื่อดูการตั้งค่าเพิ่มเติม","More settings":"การตั้งค่าเพิ่มเติม","Close":"ปิด","A new version is available":"มีเวอร์ชันใหม่","Update":"อัปเดต","Scroll up to close":"เลื่อนขึ้นเพื่อปิด","__ranked__":"จัดอันดับตัวละครทุกตัวใน {n} โหมดเกม"},
    id: {"Home":"Beranda","Upcoming games":"Game mendatang","Guides":"Panduan","All games":"Semua game","Database":"Basis data","Characters":"Karakter","Tier Lists":"Tier list","Tier List":"Tier list","Roles & Effects":"Peran & Efek","Tools":"Alat","Team Builder":"Penyusun tim","Events & Bosses":"Event & Bos","Popular games":"Game populer","New games":"Game baru","All supported games":"Semua game yang didukung","Upcoming releases":"Rilis mendatang","Latest guides":"Panduan terbaru","All upcoming games":"Semua game mendatang","Nothing announced yet.":"Belum ada pengumuman.","Database & Tools":"Basis data & Alat","Reviews, ratings and recommended builds":"Ulasan, peringkat, dan build rekomendasi","Every effect mapped to the heroes that provide it":"Setiap efek dipetakan ke hero yang menyediakannya","Plan synergy and team compositions":"Rencanakan sinergi dan komposisi tim","Optimal compositions and mechanics":"Komposisi dan mekanik optimal","No guides yet.":"Belum ada panduan.","About the tier list":"Tentang tier list","Criteria":"Kriteria","Changelog":"Catatan perubahan","No entries yet.":"Belum ada entri.","No characters match those filters.":"Tidak ada karakter yang cocok dengan filter tersebut.","↺ Reset":"↺ Atur ulang","Search characters...":"Cari karakter...","Review":"Ulasan","Ratings":"Peringkat","Recommended build":"Build rekomendasi","Pros":"Kelebihan","Cons":"Kekurangan","All guides":"Semua panduan","Every guide across every game we cover.":"Semua panduan untuk setiap game yang kami bahas.","Upcoming Games Tracker":"Pelacak game mendatang","Release date announced":"Tanggal rilis diumumkan","Games without a release date":"Game tanpa tanggal rilis","Search for a game...":"Cari game...","Release date":"Tanggal rilis","Platforms":"Platform","Publisher":"Penerbit","Website":"Situs web","Unknown":"Tidak diketahui","Search heroes or effects...":"Cari hero atau efek...","Your Team":"Tim Anda","Suggested Presets":"Preset yang disarankan","Copy URL":"Salin URL","Reset Team":"Atur ulang tim","Select Character":"Pilih karakter","Back to top":"Kembali ke atas","Theme":"Tema","Language":"Bahasa","Last updated:":"Terakhir diperbarui:","__showing__":"Menampilkan {n} karakter","__updated__":"Diperbarui {d}","__patch_updated__":"Server {p} • Diperbarui {d}","Settings":"Pengaturan","Appearance":"Tampilan","Light":"Terang","Dark":"Gelap","Scroll down for more settings":"Gulir ke bawah untuk pengaturan lainnya","More settings":"Pengaturan lainnya","Close":"Tutup","A new version is available":"Versi baru tersedia","Update":"Perbarui","Scroll up to close":"Gulir ke atas untuk menutup","__ranked__":"Setiap karakter diperingkat di {n} mode game"}
  };

  var LOCALE_TAG = { en: "en", es: "es", pt: "pt-BR", fr: "fr", de: "de", ko: "ko", ja: "ja", zh: "zh-CN", vi: "vi", th: "th", id: "id" };

  function normalize(code) {
    code = String(code || "").toLowerCase();
    if (code.indexOf("pt") === 0) return "pt";
    if (code.indexOf("zh") === 0) return "zh";
    var base = code.split("-")[0];
    if (SUPPORTED[code]) return code;
    if (SUPPORTED[base]) return base;
    return "";
  }

  function detect() {
    try { var s = localStorage.getItem("ld-lang"); if (s && SUPPORTED[s]) return s; } catch (e) {}
    var langs = (navigator.languages && navigator.languages.length) ? navigator.languages : [navigator.language || "en"];
    for (var i = 0; i < langs.length; i++) { var n = normalize(langs[i]); if (n) return n; }
    return "en";
  }

  var lang = detect();

  function tStr(s) {
    if (lang === "en") return s;
    var table = DICT[lang];
    return (table && Object.prototype.hasOwnProperty.call(table, s)) ? table[s] : s;
  }

  // Dynamic (interpolated) UI strings. Returns translated string or null.
  function tDynamic(s) {
    if (lang === "en") return null;
    var table = DICT[lang] || {}, m, tmpl;
    if ((m = /^Showing (\d+) characters?$/.exec(s)) && (tmpl = table.__showing__)) return tmpl.replace("{n}", m[1]);
    if ((m = /^Every character ranked across (\d+) game modes$/.exec(s)) && (tmpl = table.__ranked__)) return tmpl.replace("{n}", m[1]);
    if ((m = /^(.+) server • Updated (.+)$/.exec(s)) && (tmpl = table.__patch_updated__)) return tmpl.replace("{p}", m[1]).replace("{d}", m[2]);
    if ((m = /^Updated (.+)$/.exec(s)) && (tmpl = table.__updated__)) return tmpl.replace("{d}", m[1]);
    return null;
  }

  function translateOne(node) {
    var raw = node.nodeValue;
    if (!raw) return;
    var s = raw.trim();
    if (!s || s.length > 200) return;
    var out = tStr(s);
    if (out === s) { var dyn = tDynamic(s); if (dyn != null) out = dyn; }
    if (out !== s) node.nodeValue = raw.replace(s, out);
  }

  var ATTRS = ["placeholder", "title", "aria-label"];
  function translateAttrs(el) {
    for (var i = 0; i < ATTRS.length; i++) {
      var a = ATTRS[i];
      if (el.hasAttribute && el.hasAttribute(a)) {
        var v = el.getAttribute(a), t = tStr(v.trim());
        if (t !== v.trim()) el.setAttribute(a, t);
      }
    }
  }

  function translateTree(root) {
    if (lang === "en" || !root) return;
    if (root.nodeType === 3) { translateOne(root); return; }
    if (root.nodeType !== 1 && root.nodeType !== 9 && root.nodeType !== 11) return;
    if (root.querySelectorAll) {
      if (root.nodeType === 1) translateAttrs(root);
      var withAttr = root.querySelectorAll("[placeholder],[title],[aria-label]");
      for (var i = 0; i < withAttr.length; i++) translateAttrs(withAttr[i]);
    }
    var walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, null);
    var batch = [], n;
    while ((n = walker.nextNode())) batch.push(n);
    for (var j = 0; j < batch.length; j++) translateOne(batch[j]);
  }

  // Live translation: catch every dynamic re-render (grids, filters, modals).
  var observer = null;
  function startObserver() {
    if (observer || lang === "en" || !window.MutationObserver) return;
    observer = new MutationObserver(function (muts) {
      observer.disconnect();
      for (var i = 0; i < muts.length; i++) {
        var m = muts[i];
        if (m.type === "characterData") translateOne(m.target);
        else for (var k = 0; k < m.addedNodes.length; k++) {
          var nd = m.addedNodes[k];
          if (nd.nodeType === 1) translateTree(nd);
          else if (nd.nodeType === 3) translateOne(nd);
        }
      }
      observer.observe(document.body, { childList: true, subtree: true, characterData: true });
    });
    observer.observe(document.body, { childList: true, subtree: true, characterData: true });
  }

  window.LD_I18N = {
    supported: SUPPORTED,
    native: NATIVE,
    get lang() { return lang; },
    setLang: function (v) {
      if (SUPPORTED[v]) { try { localStorage.setItem("ld-lang", v); } catch (e) {} }
    },
    t: tStr,
    dynamic: tDynamic,
    translate: translateTree,
    start: startObserver,
    localeTag: function () { return LOCALE_TAG[lang] || "en"; }
  };
})();
